### ISSUE TITLE
Add Mainnet setup to the wallet so you don't have to import the file manually

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegawallet#373]
When running the current 0.9.2 vegawallet running the command `./vegawallet network list` gives the network of fairground. Now that the validators are almost live with the mainnet network we should have the config in the wallet so users can run `./vegawallet service run --network "MAINNET_NETWORK_NAME"` 

This will mitigate any issues in the community of people getting isues/errors after manually adding the mainnet config

Im not sure if this request would be covered under: https://github.com/vegaprotocol/vegawallet/issues/346  🤷‍♂️

**Comment by ValentinTrinque** [comment]
Actually we are thinking in ditching the embedded confirguration from the vegawallet, in favor of the sole usage of  `network import --from-url`

**Comment by gordsport** [comment]
https://github.com/vegaprotocol/networks/pull/69

**Comment by ValentinTrinque** [comment]
This will not be added as we removed the embedding of network configurations.

**Comment by KI-Time** [comment]
Synology DSM Docker Hypervisor Theta Edge Node Image
NOTE: No need to pull any Docker Hypervisor Image because the Synology Docker Hypervisor image thetalabs-edgelauncher_mainnet is already registered !!
1. Tap the Docker icon from the Main DSM Menu
2. Select the Registry node
3. Search for edgelauncher_mainnet
4. Double-Left Tap  thetalabsorg-edgelauncher_mainnet
Display message: Follow the setup instructions for the Synology Docker thetalabsorg-edgelauncher_mainnet image . . . 
No setup instructions found !!! 
From the Synology Docker Hypervisor Theta Edge Node Image thetalabs-edgelauncher_mainnet Terminal Tab’s BASH prompt ‘thetalabsorg-edgelauncher_mainnet1’ , , , launched with ⇒ /edgelauncher/integration/docker/node_mainnet/start.sh . . . 
 
Immediate results from the BASH Terminal session ⇒ 
* INFO[0019] Stopping the edgecore process… prefix=launcher        
* INFO[0019] Stopping the anycast process…     prefix=launcher        
* INFO[0019] anycast started.                 prefix=launcher        
* INFO[0019] Setup wallet…                    prefix=launcher        
* ERRO[0019] Failed to execute command: &{./anycast [./anycast start --config=~/.anycast/] []  <nil> 0xc00000e018 0xc00000e020 [] <nil> <nil> <nil> <nil> <nil> false [0xc000140510 0xc00000e018 0xc00000e020] [0xc000140510] [] [] <nil> <nil>}, err: fork/exec ./anycast: no such file or directory  prefix=launcher            
* WARN[0020] client.Call res: <nil>, error: Post http://127.0.0.1:7935/rpc: dial tcp 127.0.0.1:7935: connect: connection refused  prefix=launcher

I am suspecting that the WARN messages like the one above which appear in the BASH Terminal session are not a serious issue . . . But , , , the WARNs  are possibly related to what appears to be missing wallet setup instructions ??? 

I harvest Theta Fuel by Downloading Theta Edge Node for Asus 8R9SQMQ Gaming Laptop with Win10 OS OK from  https://api.thetatoken.org/downloads/edge-node/windows , , , and it created a wallet . . .  Is there a resolution worth trying for the  Synology Docker Hypervisor image thetalabs-edgelauncher_mainnet error following the Setup Wallet above using the wallet created on the Win10 laptop ???
