### ISSUE TITLE
Visual artifacts / missing characters on windows vegawallet

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vegawallet#436]
When you run the vegawallet on Windows with Powershell or Command Prompt, you see occasional weird characters on the left of the window, small boxes with question marks. See attached photo. This is in a build which includes the fix for https://github.com/vegaprotocol/vegawallet/issues/333

Repro:
1: go install code.vegaprotocol.io/vegawallet@v0.11.0
2: On Powershell or Command Prompt, run:
`vegawallet create --wallet TEST`
3: Fill in passphrase when prompted.

Expected behaviour:
All output is readable, with no visual artifacts or spurious characters.

Observed behaviour:
Some rectangles with question marks inside
![image](https://user-images.githubusercontent.com/7438348/146362686-c2589b76-df94-4c11-a5ae-0535f96d04af.png)

**Comment by pscott31** [comment]
OK so this is just because the default font for cmd.exe (which is consolas) doesn't support the ✗ ('ballot X') glyph. If you change the font to, e.g. Lucida Console, it works fine.

I'm not sure if there is anything to do here. I tried it in the new 'Windows Terminal' app and it worked with the default font there. Given that the terminal app is [slated to replace cmd.exe](https://www.ghacks.net/2021/12/17/command-prompt-to-be-replaced-by-windows-terminal-in-windows-11/), I think this problem will resolve itself with time.

I don't think there's any way to detect what font is being used so we can't dynamically turn them on or off based on if they are going to display nicely. The only thing we could do is remove all the fancy unicode ticks and crosses for all windows users, which seems like a bit of a shame.

If we think that's the right way to go, I can do that. Otherwise I think we should just close this issue.. thoughts?

**Comment by ValentinTrinque** [comment]
I don’t like the fact we should condition the display of glyphs based on the platform because it's not worth the overhead in the source code, it's just niceties. But I also don’t like that some users are just left out because of some outdated font.

I would opt for ASCII characters, such as `X ` for errors and `# ` for section title, instead of the ✗ ('ballot X') and the ➜ ('arrow right').
