### ISSUE TITLE
vegawallet running in Git Bash does not accept user input

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vegawallet#437]
vegawallet running on Git Bash outputs an error when requesting input if run from git bash on Windows. 

Repro:
1. `go install code.vegaprotocol.io/vegawallet@v0.11.0`
2. `vegawallet create --wallet TEST`

Expected behaviour:
Wallet created. All output is readable, no visual artifacts or spurious characters.

Observed behaviour:
"The handle is invalid" error is displayed to user, and no wallet is created.
![image](https://user-images.githubusercontent.com/7438348/146364640-9c226954-ba11-4672-bf66-6ce56de28f8e.png)

Notes:
- Running vegawallet in Command Prompt or Powershell works fine, other than https://github.com/vegaprotocol/vegawallet/issues/436
- Confirmed that you can workaround this issue by using --passphrase-file for this situation.

**Comment by pscott31** [comment]
OK so it turns out this is actually quite hard, and is to do with how cygwin presents something that is not quite a pty as standard input.

https://github.com/golang/go/issues/11914

I'll have a bit more of a play and see if we can get around it without too much trouble. It might be that we just have to detect running on windows/cygwin and print a warning 'password entry not supported on windows/cygwin, please use a standard windows command prompt or powershell, or specify a password using --passprase-file'

Cygwin is mostly a pile pain anyway, I don't think we should put too much effort into supporting it. It works fine if you use a standard windows terminal.

**Comment by ValentinTrinque** [comment]
We decided to raise an error requiring the user to switch to a proper windows terminal or to use the `--passphrase-file` flag.

**Comment by vega-paul** [comment]
@jgsbennett please confirm this has been fixed and provide any evidence.
