### ISSUE TITLE
Desktop wallet post-hoc json backup

### ISSUE THREAD

**Issue by zouhairstitou** [vegaprotocol/vegawallet#503]
From my own experience with lots of wallets. It is a very effective safety measure to have a post-hoc ability to backup the wallet my downloading a json file.

Nearly all wallets i have encountered, they ask once at setup to save the seed. After that they provide the ability to retrieve teh PK and json backup file.

Besides the possibility to accidently lose the seed. The new people onboarding into crypto would miss that most likely

Thanks!!

**Comment by ValentinTrinque** [comment]
Thanks for your feedback.

Indeed that's a very useful feature. However, we don't need to implement it because the wallet file is already located on your machine as encrypted JSON. 🎉 

You can find it under:
- `~/.local/share/vega` on Linux
- `LocalAppData/vega` on Windows
- `~/Library/Application Support/vega` on MacOS

**Comment by ValentinTrinque** [comment]
Closing it.
